PLUGIN_NAME=          anti-mitm
PLUGIN_VERSION=       0.1
PLUGIN_COMMENT=       Collection against L2 MITM Attacks
PLUGIN_DEPENDS=       ndpmon
PLUGIN_MAINTAINER=    franz.fabian.94@gmail.com

.include "../../Mk/plugins.mk"
